In [36]:
from tensorflow import keras
from keras.layers import Input, Dense, Dropout,Conv2D, MaxPool2D, Flatten
from tensorflow.keras import  datasets
from matplotlib import pyplot as plt

In [37]:
(x_train, y_train), (x_test, y_test) = datasets.cifar10.load_data()

In [38]:
x_train.shape

(50000, 32, 32, 3)

In [39]:
x_test.shape

(10000, 32, 32, 3)

In [40]:
#Normalize image pixel values.
x_train = x_train/255
x_test = x_test/255

In [41]:
model=keras.Sequential() #Create a network sequence.

model.add(Input(shape=(32,32,3)))
model.add(Conv2D(filters=6,kernel_size = 5,strides = (1,1), padding = 'valid',activation = 'relu'))
#model.add(Conv2D(filters=6,kernel_size = 5,strides = (1,1), padding = 'valid',activation = 'relu',input_shape = (32,32,3)))
model.add(MaxPool2D(pool_size=(2,2), strides = (2,2), padding = 'valid'))

model.add(Conv2D(filters=16,kernel_size = 5,strides = (1,1), padding = 'valid',activation = 'relu'))
model.add(MaxPool2D(pool_size=(2,2), strides = (2,2), padding = 'valid'))

model.add(Flatten())
model.add(Dense(120,activation = 'relu'))
model.add(Dense(84,activation = 'relu'))
model.add(Dense(10,activation = 'softmax'))

model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_4 (Conv2D)           (None, 28, 28, 6)         456       
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 14, 14, 6)        0         
 2D)                                                             
                                                                 
 conv2d_5 (Conv2D)           (None, 10, 10, 16)        2416      
                                                                 
 max_pooling2d_5 (MaxPooling  (None, 5, 5, 16)         0         
 2D)                                                             
                                                                 
 flatten_3 (Flatten)         (None, 400)               0         
                                                                 
 dense_9 (Dense)             (None, 120)              

In [42]:
model.compile(optimizer='Adam',loss="sparse_categorical_crossentropy",metrics=['accuracy']) 
results= model.fit(x_train,y_train,epochs=20,batch_size=128,validation_data=(x_test, y_test))



Epoch 1/20
391/391 [==============================] - 3s 6ms/step - loss: 1.7357 - accuracy: 0.3655 - val_loss: 1.5292 - val_accuracy: 0.4454
Epoch 2/20
391/391 [==============================] - 2s 5ms/step - loss: 1.4660 - accuracy: 0.4740 - val_loss: 1.3997 - val_accuracy: 0.4942
Epoch 3/20
391/391 [==============================] - 2s 5ms/step - loss: 1.3504 - accuracy: 0.5201 - val_loss: 1.3332 - val_accuracy: 0.5223
Epoch 4/20
391/391 [==============================] - 2s 5ms/step - loss: 1.2583 - accuracy: 0.5560 - val_loss: 1.2506 - val_accuracy: 0.5567
Epoch 5/20
391/391 [==============================] - 2s 5ms/step - loss: 1.1953 - accuracy: 0.5800 - val_loss: 1.2072 - val_accuracy: 0.5746
Epoch 6/20
391/391 [==============================] - 2s 5ms/step - loss: 1.1397 - accuracy: 0.5997 - val_loss: 1.2158 - val_accuracy: 0.5768
Epoch 7/20
391/391 [==============================] - 2s 5ms/step - loss: 1.0924 - accuracy: 0.6159 - val_loss: 1.1482 - val_accuracy: 0.5957
Epoch 

In [43]:
score = model.evaluate(x_test, y_test)


313/313 [==============================] - 1s 3ms/step - loss: 1.0933 - accuracy: 0.6346


In [47]:
y_pred=model.predict(x_test)
y_pred[0:3]

array([[5.0076237e-04, 2.5611328e-02, 7.5104893e-03, 7.4398118e-01,
        5.1915262e-02, 2.1120299e-02, 1.3639909e-01, 1.7395227e-03,
        1.5302604e-03, 9.6918065e-03],
       [7.9586163e-02, 7.2787303e-01, 1.0314399e-05, 1.2678183e-07,
        2.3594070e-07, 6.7275678e-08, 7.5629551e-08, 1.5355005e-07,
        1.3590303e-01, 5.6626856e-02],
       [6.0242355e-01, 2.9507503e-02, 4.2144451e-03, 4.4598349e-04,
        2.4054117e-04, 5.4159405e-04, 1.4288773e-04, 4.9163942e-04,
        3.1862351e-01, 4.3368381e-02]], dtype=float32)

In [49]:
import numpy as np
from numpy import argmax
y_pred1=argmax(y_pred,axis=1)
y_pred1[0:3]

array([3, 1, 0])

In [50]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(confusion_matrix(y_pred1,y_test))
print(accuracy_score(y_pred1,y_test))

[[675  21  62  26  25   8   6  23  74  34]
 [ 40 804  16  22  13  10  14  11  59 123]
 [ 62   9 552 107 120 102  69  50  17  20]
 [ 14  10  68 400  55 193  54  42  16   9]
 [ 19   8  88  83 552  62  23  72   9  14]
 [  8   4  61 162  39 471  34  78   9  13]
 [ 20  25  72 114  94  67 765  22  14  20]
 [  3   5  32  26  69  57   6 660   2  16]
 [112  25  27  24  20  17  10   3 757  41]
 [ 47  89  22  36  13  13  19  39  43 710]]
0.6346
