In [27]:
from tensorflow import keras
from keras.layers import Input, Dense, Dropout,Conv2D, MaxPooling2D, Flatten
from tensorflow.keras import  datasets
from matplotlib import pyplot as plt

In [28]:
(x_train, y_train), (x_test, y_test) = datasets.cifar10.load_data()

In [29]:
x_train.shape

(50000, 32, 32, 3)

In [30]:
x_test.shape

(10000, 32, 32, 3)

In [31]:
#Normalize image pixel values.
x_train = x_train/255
x_test = x_test/255

In [32]:
model=keras.Sequential() #Create a network sequence.

model.add(Input(shape=(32,32,3)))
model.add(Conv2D(32, (3, 3), padding='same',activation='relu'))
#model.add(Conv2D(32, (3, 3), padding='same', activation='relu', input_shape=(32,32,3)))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Conv2D(64, (3, 3), padding='same', activation='relu'))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Conv2D(64, (3, 3), padding='same', activation='relu'))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(10, activation='softmax'))

In [33]:
model.compile(optimizer='Adam',loss="sparse_categorical_crossentropy",metrics=['accuracy']) 
results= model.fit(x_train,y_train,epochs=20,batch_size=128,validation_data=(x_test, y_test))



Epoch 1/20
391/391 [==============================] - 157s 401ms/step - loss: 1.7742 - accuracy: 0.3312 - val_loss: 1.4111 - val_accuracy: 0.4762
Epoch 2/20
391/391 [==============================] - 156s 399ms/step - loss: 1.3248 - accuracy: 0.5166 - val_loss: 1.2202 - val_accuracy: 0.5601
Epoch 3/20
391/391 [==============================] - 157s 401ms/step - loss: 1.1594 - accuracy: 0.5802 - val_loss: 1.0616 - val_accuracy: 0.6250
Epoch 4/20
391/391 [==============================] - 157s 401ms/step - loss: 1.0560 - accuracy: 0.6215 - val_loss: 0.9249 - val_accuracy: 0.6698
Epoch 5/20
391/391 [==============================] - 157s 401ms/step - loss: 0.9724 - accuracy: 0.6533 - val_loss: 0.8968 - val_accuracy: 0.6891
Epoch 6/20
391/391 [==============================] - 157s 401ms/step - loss: 0.8998 - accuracy: 0.6779 - val_loss: 0.8401 - val_accuracy: 0.7039
Epoch 7/20
391/391 [==============================] - 157s 401ms/step - loss: 0.8443 - accuracy: 0.7008 - val_loss: 0.7855 -

In [34]:
score = model.evaluate(x_test, y_test)


313/313 [==============================] - 8s 26ms/step - loss: 0.5881 - accuracy: 0.8019


In [35]:
y_pred=model.predict(x_test)
y_pred[0:3]

array([[2.7163900e-04, 3.2132107e-03, 1.4195467e-03, 6.9616461e-01,
        3.4877294e-04, 2.6107654e-01, 3.5315517e-02, 1.1790473e-03,
        6.1826344e-04, 3.9288329e-04],
       [1.0811333e-02, 1.0433994e-01, 4.1965663e-07, 4.4686685e-06,
        1.2815647e-07, 3.1810014e-08, 5.5820863e-08, 2.4172530e-07,
        8.7238210e-01, 1.2461284e-02],
       [1.9053901e-02, 3.0300581e-01, 1.2978271e-04, 1.0896876e-03,
        2.1764536e-05, 5.6710844e-05, 7.3824012e-05, 1.3517588e-04,
        6.2272805e-01, 5.3705323e-02]], dtype=float32)

In [36]:
import numpy as np
from numpy import argmax
y_pred1=argmax(y_pred,axis=1)
y_pred1[0:3]

array([3, 8, 8])

In [37]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(confusion_matrix(y_pred1,y_test))
print(accuracy_score(y_pred1,y_test))

[[859   6  76  25  10  16   9  16  67  22]
 [ 12 938   2   8   4   2   3   0  40  60]
 [ 19   1 641  40  39  23  31   7   8   4]
 [  8   3  38 596  44  95  43  20   9  10]
 [ 14   0  78  49 769  36  18  35   3   4]
 [  3   3  70 168  35 754  19  35   2   1]
 [  4   8  52  59  37  18 864   7   4   4]
 [ 16   2  30  33  56  47   7 876   2   4]
 [ 38   5   4  13   4   5   3   1 843  12]
 [ 27  34   9   9   2   4   3   3  22 879]]
0.8019
