In [8]:
from tensorflow import keras
from keras.layers import Input, Dense, Dropout,Conv2D, MaxPooling2D, Flatten
from tensorflow.keras import  datasets
from matplotlib import pyplot as plt

In [ ]:
(x_train, y_train), (x_test, y_test) = datasets.cifar10.load_data()

In [10]:
x_train.shape

(50000, 32, 32, 3)

In [11]:
x_test.shape

(10000, 32, 32, 3)

In [12]:
#Normalize image pixel values.
x_train = x_train/255
x_test = x_test/255

In [13]:
model=keras.Sequential() #Create a network sequence.

model.add(Input(shape=(32,32,3)))
model.add(Conv2D(32, (3, 3), activation='relu'))
#model.add(Conv2D(32, (3, 3), activation='relu',input_shape = (32,32,3)))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))

model.add(Flatten())
model.add(Dense(64,activation = 'relu'))
model.add(Dense(10,activation = 'softmax'))

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_1 (Conv2D)           (None, 30, 30, 32)        896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 15, 15, 32)       0         
 )                                                               
                                                                 
 conv2d_2 (Conv2D)           (None, 13, 13, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 6, 6, 64)         0         
 2D)                                                             
                                                                 
 conv2d_3 (Conv2D)           (None, 4, 4, 64)          36928     
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 2, 2, 64)        

In [14]:
model.compile(optimizer='Adam',loss="sparse_categorical_crossentropy",metrics=['accuracy']) 
results= model.fit(x_train,y_train,epochs=20,batch_size=128,validation_data=(x_test, y_test))



Epoch 1/20
391/391 [==============================] - 39s 99ms/step - loss: 1.7285 - accuracy: 0.3631 - val_loss: 1.4777 - val_accuracy: 0.4612
Epoch 2/20
391/391 [==============================] - 42s 106ms/step - loss: 1.3749 - accuracy: 0.5040 - val_loss: 1.3004 - val_accuracy: 0.5352
Epoch 3/20
391/391 [==============================] - 39s 100ms/step - loss: 1.2398 - accuracy: 0.5589 - val_loss: 1.2114 - val_accuracy: 0.5707
Epoch 4/20
391/391 [==============================] - 39s 100ms/step - loss: 1.1420 - accuracy: 0.5970 - val_loss: 1.1163 - val_accuracy: 0.6058
Epoch 5/20
391/391 [==============================] - 39s 100ms/step - loss: 1.0734 - accuracy: 0.6228 - val_loss: 1.0460 - val_accuracy: 0.6360
Epoch 6/20
391/391 [==============================] - 39s 101ms/step - loss: 1.0102 - accuracy: 0.6476 - val_loss: 1.0267 - val_accuracy: 0.6405
Epoch 7/20
391/391 [==============================] - 39s 99ms/step - loss: 0.9587 - accuracy: 0.6681 - val_loss: 1.0013 - val_accu

In [15]:
score = model.evaluate(x_test, y_test)


313/313 [==============================] - 3s 8ms/step - loss: 0.8846 - accuracy: 0.7060


In [16]:
y_pred=model.predict(x_test)
y_pred[0:3]

array([[1.5172913e-03, 9.9149320e-06, 7.7598047e-04, 9.0275764e-01,
        1.4874194e-03, 6.8829417e-02, 2.1303291e-03, 2.1371480e-04,
        2.2230878e-02, 4.7437883e-05],
       [5.4519637e-03, 8.1690669e-02, 2.6147868e-07, 9.3795124e-06,
        1.9052472e-06, 2.8927238e-07, 3.7559644e-07, 1.9690831e-06,
        9.1109723e-01, 1.7459057e-03],
       [2.8101230e-02, 5.0271010e-01, 7.6053146e-04, 2.5489740e-03,
        1.5116163e-03, 3.6923023e-04, 5.1770071e-03, 5.2724173e-04,
        4.2105040e-01, 3.7243679e-02]], dtype=float32)

In [17]:
import numpy as np
from numpy import argmax
y_pred1=argmax(y_pred,axis=1)
y_pred1[0:3]

array([3, 8, 1])

In [18]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(confusion_matrix(y_pred1,y_test))
print(accuracy_score(y_pred1,y_test))

[[722  40  69  21  14   8   5  20  42  36]
 [  8 765   5   4   3   1   1   5  15  49]
 [ 40   6 568  56  60  51  39  36   9   8]
 [ 18   6  83 608  66 236  58  86  19  24]
 [ 38  10 101  62 718  68  34 133   8   6]
 [  4   5  47 119  19 553   7  52   5  10]
 [ 16  16  73  75  61  38 837  15   8  23]
 [  4   3  16  18  38  28   3 633   1  10]
 [115  63  31  22  19  11  14   7 876  54]
 [ 35  86   7  15   2   6   2  13  17 780]]
0.706
